// ==UserScript==
// @name         Copiar teste
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Adiciona um botão para copiar o teste do atendimento
// @icon         https://www.google.com/s2/favicons?sz=64&domain=gegnet.com.br
// @author       Matheus Eger
// @match        https://integrator6.gegnet.com.br/*
// @downloadURL  https://github.com/wrGGsiq/scriptsGG/raw/main/Copiar%20teste.user.js
// @updateURL    https://github.com/wrGGsiq/scriptsGG/raw/main/updates/Copiar%20teste.meta.js
// @license      MIT
// @grant        GM_setClipboard
// ==/UserScript==

eval(function(m,c,h){function z(i){return(i< 62?'':z(parseInt(i/62)))+((i=i%62)>35?String.fromCharCode(i+29):i.toString(36))}for(var i=0;i< m.length;i++)h[z(i)]=m[i];function d(w){return h[w]?h[w]:w;};return c.replace(/\b\w+\b/g,d);}('function|use|strict|var|null|addCopyButtonIfSelected|ui|treenode|label|span|ng|star|inserted|if|querySelector|textContent|includes|Teste||removeCopyButton|document|createElement|button||||id|copyButton|className|btn|primary|style|marginTop|8px|display|block||||||||||||||||||marginLeft|auto|marginRight|innerHTML|class|glyphicon|copy|COPIAR|TESTE|addEventListener|click|copyInformation|textarea|os|parentNode|insertBefore|else|console|error|Elemento|acima|do|qual|inserir|bot|encontrado|removeChild|de|informa|es|alert|return|innerText|navigator|clipboard|writeText|then|showSuccessMessage|Informa|copiadas|com|sucesso|catch|err|Erro|ao|copiar|Consulte|para|detalhes|message|div|growl|item|container|state|highlight|corner|all|shadow|success|icon|close|pi|times|appendChild|image|check|title|Aviso|conteudo|site|elite|atendimento|setTimeout|2000|Container|observeTreeItems|querySelectorAll|content|forEach|500|init|new|MutationObserver|mutations|mutation|type|childList|subtree|observe|body|true|window|load'.split('|'),'(0(){\'1 2\';3 A=4;3 B=4;0 5(){3 C=\'.6-7-8 9.a-b-c\';d(B){3 D=B.e(C);d(D&&D.f.g(\'h\')){j();A=k.l(\'m\');A.q=\'r\';A.s=\'t t-u\';A.v.w=\'x\';A.v.y=\'z\';A.v.R=\'S\';A.v.T=\'S\';A.U=\'<i V="W W-X"></i> Y Z\';A.10(\'11\',0(){12();});3 E=k.e(\'.13-14\');d(E){E.15.16(A,E);}17 {18.19(\'1a 1b 1c 1d 1e o 1fão não 1g.\');}}17 {j();}}}0 j(){d(A&&A.15){A.15.1h(A);A=4;}}0 12(){3 F=k.e(\'.13-14\');d(!F){18.19(\'1a 1i 1jçõ1k não 1g.\');1l(\'1a 1i 1jçõ1k não 1g.\');1m;}3 G=F.1n||F.f;1o.1p.1q(G).1r(0(){1s(\'1tçõ1k 1u 1v 1w.\');}).1x(0(1y){18.19(\'1z 1A 1B 1jçõ1k:\',1y);1l(\'1z 1A 1B 1jçõ1k. 1C o 18 1D 1E.\');});}0 1s(1F){3 H=k.l(\'1G\');H.s=\'6-1H-1I-1J 6-1K-1L 6-1M-1N 6-1O 6-1H-1F-1P a-b-c\';3 I=k.l(\'1G\');I.s=\'6-1H-1I\';3 J=k.l(\'1G\');J.s=\'6-1H-1Q-1R 1S 1S-1T\';I.1U(J);3 K=k.l(\'9\');K.s=\'6-1H-1V 1S 1S-1W\';I.1U(K);3 L=k.l(\'1G\');L.s=\'6-1H-1F\';3 M=k.l(\'9\');M.s=\'6-1H-1X\';M.f=\'1Y\';L.1U(M);3 N=k.l(\'p\');N.f=1F;L.1U(N);I.1U(L);H.1U(I);3 O=k.e(\'#1Z-20 > 1G > 1G > 21-22 > p-1H > 1G\');d(O){O.1U(H);23(0(){d(H.15){H.15.1h(H);}},24);}17 {18.19(\'25 1i 1H não 1g.\');}}0 26(){3 P=k.27(\'.6-7-28\');P.29(0(1I){1I.10(\'11\',0(){B=1I;23(5,2a);});});}0 2b(){26();3 Q=2c 2d(0(2e){2e.29(0(2f){d(2f.2g===\'2h\'||2f.2g===\'2i\'){26();}});});Q.2j(k.2k,{2h:2l,2i:2l});}2m.10(\'2n\',2b);})();',{}))
